version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_DB: webchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webchat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=webchat
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key-change-in-production
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - webchat-network
    restart: unless-stopped

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: chat
    environment:
      - AUTH_SERVICE_URL=auth-service:50051
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=webchat
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - postgres
    networks:
      - webchat-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  webchat-network:
    driver: bridge